<?php

namespace Database\Seeders;

use App\Models\Carrier;
use App\Models\CarrierProduct;
use Illuminate\Database\Seeder;

class CarrierSeeder extends Seeder
{
    /** All 50 US states + DC for national carriers */
    private const ALL_STATES = [
        'AL','AK','AZ','AR','CA','CO','CT','DC','DE','FL','GA','HI','ID','IL','IN',
        'IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH',
        'NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT',
        'VT','VA','WA','WV','WI','WY',
    ];

    public function run(): void
    {
        foreach ($this->carriers() as $carrierData) {
            $products = $carrierData['products'] ?? [];
            unset($carrierData['products']);

            $carrier = Carrier::updateOrCreate(
                ['slug' => $carrierData['slug']],
                $carrierData
            );

            foreach ($products as $productData) {
                CarrierProduct::updateOrCreate(
                    ['carrier_id' => $carrier->id, 'name' => $productData['name']],
                    [...$productData, 'carrier_id' => $carrier->id]
                );
            }
        }
    }

    private function carriers(): array
    {
        $all = self::ALL_STATES;

        return [
            // ─── P&C / Personal Lines ───────────────────────────
            [
                'name' => 'State Farm', 'slug' => 'state-farm',
                'naic_code' => '25178', 'naic_group_code' => '0176',
                'domicile_state' => 'IL', 'am_best_rating' => 'A++',
                'am_best_financial_size' => 'XV', 'year_founded' => 1922,
                'naic_complaint_ratio' => 0.62, 'market_segment' => 'multi',
                'distribution_model' => 'captive',
                'headquarters_city' => 'Bloomington', 'headquarters_state' => 'IL',
                'total_premium_written' => 82000.00, 'is_admitted' => true,
                'description' => 'America\'s largest auto and home insurance provider.',
                'lines_of_business' => ['auto','homeowners','renters','condo','life_term','life_whole','umbrella_personal','flood','health_individual'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'State Farm Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 80, 'max_premium' => 250, 'deductible_options' => [250,500,1000,2000], 'coverage_options' => ['$25,000','$50,000','$100,000','$250,000','$500,000'], 'features' => ['Roadside Assistance','Rental Reimbursement','Good Driver Discount','Steer Clear']],
                    ['name' => 'State Farm Homeowners', 'insurance_type' => 'homeowners', 'rate_table_product_type' => 'homeowners', 'min_premium' => 100, 'max_premium' => 400, 'deductible_options' => [500,1000,2500,5000], 'coverage_options' => ['$200,000','$350,000','$500,000','$750,000','$1,000,000'], 'features' => ['Replacement Cost','Personal Property','Liability Protection','Medical Payments']],
                    ['name' => 'State Farm Renters', 'insurance_type' => 'renters', 'rate_table_product_type' => 'renters', 'min_premium' => 15, 'max_premium' => 40, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$20,000','$30,000','$50,000','$100,000'], 'features' => ['Personal Property','Liability','Loss of Use']],
                    ['name' => 'State Farm Term Life', 'insurance_type' => 'life_term', 'rate_table_product_type' => 'life_term', 'min_premium' => 20, 'max_premium' => 150, 'deductible_options' => [], 'coverage_options' => ['$100,000','$250,000','$500,000','$1,000,000'], 'features' => ['Level Premium','Convertible','Accelerated Benefits']],
                    ['name' => 'State Farm Whole Life', 'insurance_type' => 'life_whole', 'rate_table_product_type' => 'life_whole', 'min_premium' => 50, 'max_premium' => 300, 'deductible_options' => [], 'coverage_options' => ['$25,000','$50,000','$100,000','$250,000'], 'features' => ['Cash Value','Guaranteed Issue Options','Dividend Eligible']],
                ],
            ],
            [
                'name' => 'GEICO', 'slug' => 'geico',
                'naic_code' => '22063', 'naic_group_code' => '0048',
                'domicile_state' => 'MD', 'am_best_rating' => 'A++',
                'am_best_financial_size' => 'XV', 'year_founded' => 1936,
                'naic_complaint_ratio' => 0.85, 'market_segment' => 'personal',
                'distribution_model' => 'direct',
                'headquarters_city' => 'Chevy Chase', 'headquarters_state' => 'MD',
                'total_premium_written' => 42000.00,
                'description' => 'Known for competitive auto insurance rates and direct-to-consumer model.',
                'lines_of_business' => ['auto','homeowners','renters','condo','motorcycle','boat_watercraft','umbrella_personal','life_term'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'GEICO Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 65, 'max_premium' => 220, 'deductible_options' => [250,500,1000,2500], 'coverage_options' => ['$25,000','$50,000','$100,000','$300,000'], 'features' => ['Multi-Policy Discount','Military Discount','Accident Forgiveness','Mechanical Breakdown']],
                    ['name' => 'GEICO Homeowners', 'insurance_type' => 'homeowners', 'rate_table_product_type' => 'homeowners', 'min_premium' => 95, 'max_premium' => 380, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$200,000','$350,000','$500,000'], 'features' => ['Replacement Cost','Personal Property','Bundled Savings']],
                    ['name' => 'GEICO Renters', 'insurance_type' => 'renters', 'rate_table_product_type' => 'renters', 'min_premium' => 12, 'max_premium' => 30, 'deductible_options' => [250,500], 'coverage_options' => ['$15,000','$30,000','$50,000','$100,000'], 'features' => ['Personal Property','Liability','Additional Living Expenses']],
                    ['name' => 'GEICO Motorcycle', 'insurance_type' => 'motorcycle', 'rate_table_product_type' => 'motorcycle', 'min_premium' => 30, 'max_premium' => 120, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$25,000','$50,000','$100,000'], 'features' => ['Accessory Coverage','Total Loss Coverage','Roadside Assistance']],
                ],
            ],
            [
                'name' => 'Progressive', 'slug' => 'progressive',
                'naic_code' => '24260', 'naic_group_code' => '0155',
                'domicile_state' => 'OH', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XV', 'year_founded' => 1937,
                'naic_complaint_ratio' => 0.91, 'market_segment' => 'personal',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'Mayfield Village', 'headquarters_state' => 'OH',
                'total_premium_written' => 58000.00,
                'description' => 'Innovative auto insurer with usage-based and comparison tools.',
                'lines_of_business' => ['auto','homeowners','renters','condo','motorcycle','boat_watercraft','rv_motorhome','umbrella_personal','commercial_auto','bop'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Progressive Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 70, 'max_premium' => 230, 'deductible_options' => [250,500,1000,2500], 'coverage_options' => ['$25,000','$50,000','$100,000','$250,000','$500,000'], 'features' => ['Snapshot Usage-Based','Name Your Price','Multi-Car Discount','Pet Injury Coverage']],
                    ['name' => 'Progressive Homeowners', 'insurance_type' => 'homeowners', 'rate_table_product_type' => 'homeowners', 'min_premium' => 90, 'max_premium' => 360, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$200,000','$350,000','$500,000','$750,000'], 'features' => ['HomeQuote Explorer','Bundle Discount','Equipment Breakdown']],
                    ['name' => 'Progressive Commercial Auto', 'insurance_type' => 'commercial_auto', 'rate_table_product_type' => 'commercial_auto', 'min_premium' => 120, 'max_premium' => 400, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000'], 'features' => ['Fleet Discount','Hired & Non-Owned','Cargo Coverage']],
                    ['name' => 'Progressive BOP', 'insurance_type' => 'bop', 'rate_table_product_type' => 'bop', 'min_premium' => 100, 'max_premium' => 350, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$300,000','$500,000','$1,000,000'], 'features' => ['GL + Property Combined','Business Income','Equipment Breakdown']],
                ],
            ],
            [
                'name' => 'Allstate', 'slug' => 'allstate',
                'naic_code' => '19232', 'naic_group_code' => '0008',
                'domicile_state' => 'IL', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XV', 'year_founded' => 1931,
                'naic_complaint_ratio' => 1.05, 'market_segment' => 'multi',
                'distribution_model' => 'captive',
                'headquarters_city' => 'Northbrook', 'headquarters_state' => 'IL',
                'total_premium_written' => 45000.00,
                'description' => 'You\'re in good hands — comprehensive personal and commercial coverage.',
                'lines_of_business' => ['auto','homeowners','renters','condo','life_term','life_whole','umbrella_personal','motorcycle','bop'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Allstate Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 85, 'max_premium' => 260, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$25,000','$50,000','$100,000','$300,000'], 'features' => ['Safe Driving Bonus','New Car Replacement','Deductible Rewards','Accident Forgiveness']],
                    ['name' => 'Allstate Homeowners', 'insurance_type' => 'homeowners', 'rate_table_product_type' => 'homeowners', 'min_premium' => 105, 'max_premium' => 400, 'deductible_options' => [500,1000,2500,5000], 'coverage_options' => ['$200,000','$350,000','$500,000','$750,000'], 'features' => ['Claim-Free Discount','HostAdvantage','Green Improvement']],
                    ['name' => 'Allstate Term Life', 'insurance_type' => 'life_term', 'rate_table_product_type' => 'life_term', 'min_premium' => 25, 'max_premium' => 140, 'deductible_options' => [], 'coverage_options' => ['$100,000','$250,000','$500,000','$1,000,000'], 'features' => ['Level Premium','Convertible','Living Benefits']],
                ],
            ],
            [
                'name' => 'USAA', 'slug' => 'usaa',
                'naic_code' => '25941', 'naic_group_code' => '0620',
                'domicile_state' => 'TX', 'am_best_rating' => 'A++',
                'am_best_financial_size' => 'XV', 'year_founded' => 1922,
                'naic_complaint_ratio' => 0.44, 'market_segment' => 'personal',
                'distribution_model' => 'direct',
                'headquarters_city' => 'San Antonio', 'headquarters_state' => 'TX',
                'total_premium_written' => 30000.00,
                'description' => 'Top-rated insurance exclusively for military members and families.',
                'lines_of_business' => ['auto','homeowners','renters','life_term','life_whole','umbrella_personal'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'USAA Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 60, 'max_premium' => 190, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$50,000','$100,000','$250,000','$500,000'], 'features' => ['Military Discount','Safe Pilot Discount','Accident Forgiveness','Rideshare Coverage']],
                    ['name' => 'USAA Homeowners', 'insurance_type' => 'homeowners', 'rate_table_product_type' => 'homeowners', 'min_premium' => 90, 'max_premium' => 350, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$200,000','$350,000','$500,000','$750,000'], 'features' => ['Replacement Cost','Personal Property','Military Relocation']],
                    ['name' => 'USAA Renters', 'insurance_type' => 'renters', 'rate_table_product_type' => 'renters', 'min_premium' => 10, 'max_premium' => 28, 'deductible_options' => [250,500], 'coverage_options' => ['$25,000','$50,000','$100,000'], 'features' => ['Personal Property','Liability','Military Housing']],
                ],
            ],
            [
                'name' => 'Liberty Mutual', 'slug' => 'liberty-mutual',
                'naic_code' => '23043', 'naic_group_code' => '0111',
                'domicile_state' => 'MA', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'XV', 'year_founded' => 1912,
                'naic_complaint_ratio' => 1.12, 'market_segment' => 'multi',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'Boston', 'headquarters_state' => 'MA',
                'total_premium_written' => 48000.00,
                'description' => 'Global insurer with customizable personal and commercial coverage.',
                'lines_of_business' => ['auto','homeowners','renters','condo','umbrella_personal','commercial_gl','bop','workers_comp'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Liberty Mutual Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 80, 'max_premium' => 240, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$50,000','$100,000','$250,000'], 'features' => ['New Car Replacement','Better Car Replacement','Lifetime Repair Guarantee']],
                    ['name' => 'Liberty Mutual Homeowners', 'insurance_type' => 'homeowners', 'rate_table_product_type' => 'homeowners', 'min_premium' => 95, 'max_premium' => 380, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$200,000','$350,000','$500,000'], 'features' => ['Inflation Protection','Water Backup','Identity Theft']],
                    ['name' => 'Liberty Mutual Workers Comp', 'insurance_type' => 'workers_comp', 'rate_table_product_type' => 'workers_comp', 'min_premium' => 200, 'max_premium' => 800, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['State Statutory Limits','$500,000','$1,000,000'], 'features' => ['Pay-As-You-Go','Loss Control','Return-to-Work Programs']],
                ],
            ],
            [
                'name' => 'Nationwide', 'slug' => 'nationwide',
                'naic_code' => '23787', 'naic_group_code' => '0495',
                'domicile_state' => 'OH', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XV', 'year_founded' => 1926,
                'naic_complaint_ratio' => 0.78, 'market_segment' => 'multi',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Columbus', 'headquarters_state' => 'OH',
                'total_premium_written' => 25000.00,
                'description' => 'Nationwide is on your side — comprehensive plans across all lines.',
                'lines_of_business' => ['auto','homeowners','renters','life_term','life_whole','annuity','umbrella_personal','commercial_gl','bop','workers_comp','commercial_auto'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Nationwide Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 78, 'max_premium' => 225, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$50,000','$100,000','$250,000'], 'features' => ['Vanishing Deductible','Accident Forgiveness','On Your Side Review']],
                    ['name' => 'Nationwide BOP', 'insurance_type' => 'bop', 'rate_table_product_type' => 'bop', 'min_premium' => 150, 'max_premium' => 500, 'deductible_options' => [500,1000,2500,5000], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000'], 'features' => ['GL + Property','Business Income','Equipment Breakdown','Cyber Coverage']],
                ],
            ],
            [
                'name' => 'Farmers Insurance', 'slug' => 'farmers',
                'naic_code' => '21652', 'naic_group_code' => '0306',
                'domicile_state' => 'CA', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'XV', 'year_founded' => 1928,
                'naic_complaint_ratio' => 1.18, 'market_segment' => 'personal',
                'distribution_model' => 'captive',
                'headquarters_city' => 'Woodland Hills', 'headquarters_state' => 'CA',
                'total_premium_written' => 23000.00,
                'description' => 'We know a thing or two because we\'ve seen a thing or two.',
                'lines_of_business' => ['auto','homeowners','renters','condo','umbrella_personal','life_term','bop'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Farmers Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 88, 'max_premium' => 255, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$50,000','$100,000','$300,000'], 'features' => ['Signal Discount','Multi-Policy Savings','New Car Pledge']],
                    ['name' => 'Farmers Umbrella', 'insurance_type' => 'umbrella_personal', 'rate_table_product_type' => 'umbrella_personal', 'min_premium' => 20, 'max_premium' => 60, 'deductible_options' => [], 'coverage_options' => ['$1,000,000','$2,000,000','$5,000,000'], 'features' => ['Excess Liability','Personal Injury','Worldwide Coverage']],
                ],
            ],
            [
                'name' => 'Travelers', 'slug' => 'travelers',
                'naic_code' => '25658', 'naic_group_code' => '3548',
                'domicile_state' => 'CT', 'am_best_rating' => 'A++',
                'am_best_financial_size' => 'XV', 'year_founded' => 1853,
                'naic_complaint_ratio' => 0.72, 'market_segment' => 'multi',
                'distribution_model' => 'independent',
                'headquarters_city' => 'New York', 'headquarters_state' => 'NY',
                'total_premium_written' => 36000.00,
                'description' => 'One of America\'s oldest carriers — leaders in commercial and personal lines.',
                'lines_of_business' => ['auto','homeowners','renters','condo','umbrella_personal','commercial_gl','commercial_property','bop','workers_comp','commercial_auto','professional_liability','cyber_liability','directors_officers','inland_marine','surety_bond','umbrella_commercial'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Travelers Homeowners', 'insurance_type' => 'homeowners', 'rate_table_product_type' => 'homeowners', 'min_premium' => 105, 'max_premium' => 420, 'deductible_options' => [500,1000,2500,5000], 'coverage_options' => ['$200,000','$400,000','$600,000','$1,000,000'], 'features' => ['Green Home Discount','Wildfire Defense','Cyber Coverage']],
                    ['name' => 'Travelers BOP', 'insurance_type' => 'bop', 'rate_table_product_type' => 'bop', 'min_premium' => 150, 'max_premium' => 600, 'deductible_options' => [500,1000,2500,5000], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000','$5,000,000'], 'features' => ['GL + Property','Professional Liability','Cyber Insurance','Commercial Auto']],
                    ['name' => 'Travelers Workers Comp', 'insurance_type' => 'workers_comp', 'rate_table_product_type' => 'workers_comp', 'min_premium' => 180, 'max_premium' => 750, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['State Statutory','$500,000','$1,000,000'], 'features' => ['Pay-As-You-Go','Nurse Triage','Return-to-Work']],
                    ['name' => 'Travelers Cyber', 'insurance_type' => 'cyber_liability', 'rate_table_product_type' => 'cyber_liability', 'min_premium' => 80, 'max_premium' => 500, 'deductible_options' => [1000,2500,5000,10000], 'coverage_options' => ['$250,000','$500,000','$1,000,000','$5,000,000'], 'features' => ['Data Breach Response','Business Interruption','Cyber Extortion','Media Liability']],
                ],
            ],
            [
                'name' => 'Erie Insurance', 'slug' => 'erie-insurance',
                'naic_code' => '26263', 'naic_group_code' => '0343',
                'domicile_state' => 'PA', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XIV', 'year_founded' => 1925,
                'naic_complaint_ratio' => 0.35, 'market_segment' => 'personal',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Erie', 'headquarters_state' => 'PA',
                'total_premium_written' => 9000.00,
                'description' => 'Highest customer satisfaction in auto insurance — 12-state regional carrier.',
                'lines_of_business' => ['auto','homeowners','renters','life_term','life_whole','umbrella_personal','bop','workers_comp','commercial_auto'],
                'states_available' => ['DC','IL','IN','KY','MD','NC','NY','OH','PA','TN','VA','WI','WV'],
                'products' => [
                    ['name' => 'Erie Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 70, 'max_premium' => 200, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$50,000','$100,000','$250,000','$500,000'], 'features' => ['Rate Lock','Diminishing Deductible','First Accident Forgiveness']],
                    ['name' => 'Erie Homeowners', 'insurance_type' => 'homeowners', 'rate_table_product_type' => 'homeowners', 'min_premium' => 85, 'max_premium' => 350, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$200,000','$350,000','$500,000'], 'features' => ['Guaranteed Replacement Cost','Water Backup','Identity Recovery']],
                ],
            ],
            [
                'name' => 'American Family', 'slug' => 'american-family',
                'naic_code' => '19275', 'naic_group_code' => '0477',
                'domicile_state' => 'WI', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'XIV', 'year_founded' => 1927,
                'naic_complaint_ratio' => 0.82, 'market_segment' => 'personal',
                'distribution_model' => 'captive',
                'headquarters_city' => 'Madison', 'headquarters_state' => 'WI',
                'total_premium_written' => 14000.00,
                'description' => 'Midwestern carrier focused on personal lines and small business.',
                'lines_of_business' => ['auto','homeowners','renters','umbrella_personal','life_term','bop'],
                'states_available' => ['AZ','CO','GA','IA','ID','IL','IN','KS','MN','MO','MT','ND','NE','NV','OH','OR','SD','UT','WA','WI'],
                'products' => [
                    ['name' => 'AmFam Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 75, 'max_premium' => 210, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$50,000','$100,000','$250,000'], 'features' => ['KnowYourDrive','Multi-Policy','Teen Driver']],
                    ['name' => 'AmFam Homeowners', 'insurance_type' => 'homeowners', 'rate_table_product_type' => 'homeowners', 'min_premium' => 90, 'max_premium' => 340, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$200,000','$350,000','$500,000'], 'features' => ['Replacement Cost','DreamProtect','Claims-Free Discount']],
                ],
            ],
            [
                'name' => 'Auto-Owners Insurance', 'slug' => 'auto-owners',
                'naic_code' => '18988', 'naic_group_code' => '0091',
                'domicile_state' => 'MI', 'am_best_rating' => 'A++',
                'am_best_financial_size' => 'XIV', 'year_founded' => 1916,
                'naic_complaint_ratio' => 0.41, 'market_segment' => 'multi',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Lansing', 'headquarters_state' => 'MI',
                'total_premium_written' => 10000.00,
                'description' => 'Top-rated regional carrier known for exceptional claims handling.',
                'lines_of_business' => ['auto','homeowners','life_term','life_whole','bop','workers_comp','umbrella_personal'],
                'states_available' => ['AL','AR','AZ','CO','FL','GA','IA','ID','IL','IN','KS','KY','MI','MN','MO','NC','ND','NE','OH','PA','SC','SD','TN','UT','VA','WI'],
                'products' => [
                    ['name' => 'Auto-Owners Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 72, 'max_premium' => 195, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$50,000','$100,000','$250,000','$500,000'], 'features' => ['Broad Coverage','Multi-Policy Savings','Claims-Free Rewards']],
                ],
            ],
            [
                'name' => 'Chubb', 'slug' => 'chubb',
                'naic_code' => '20281', 'naic_group_code' => '0218',
                'domicile_state' => 'PA', 'am_best_rating' => 'A++',
                'am_best_financial_size' => 'XV', 'year_founded' => 1882,
                'naic_complaint_ratio' => 0.52, 'market_segment' => 'multi',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Whitehouse Station', 'headquarters_state' => 'NJ',
                'total_premium_written' => 42000.00,
                'description' => 'World\'s largest publicly traded P&C insurer — premium high-net-worth coverage.',
                'lines_of_business' => ['auto','homeowners','umbrella_personal','commercial_gl','commercial_property','professional_liability','cyber_liability','directors_officers','umbrella_commercial','inland_marine','jewelry_valuables'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Chubb Masterpiece Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 150, 'max_premium' => 500, 'deductible_options' => [500,1000,2500,5000], 'coverage_options' => ['$250,000','$500,000','$1,000,000'], 'features' => ['Agreed Value','OEM Parts','Worldwide Coverage','New Car Replacement']],
                    ['name' => 'Chubb Masterpiece Home', 'insurance_type' => 'homeowners', 'rate_table_product_type' => 'homeowners', 'min_premium' => 200, 'max_premium' => 800, 'deductible_options' => [1000,2500,5000,10000], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000','$5,000,000'], 'features' => ['Extended Replacement Cost','Cash Settlement','HomeScan Appraisal','Sewer Backup']],
                    ['name' => 'Chubb Valuable Articles', 'insurance_type' => 'jewelry_valuables', 'rate_table_product_type' => 'jewelry_valuables', 'min_premium' => 30, 'max_premium' => 200, 'deductible_options' => [0,250,500], 'coverage_options' => ['$25,000','$50,000','$100,000','$500,000'], 'features' => ['Agreed Value','Worldwide Coverage','No Deductible Option','Newly Acquired']],
                    ['name' => 'Chubb D&O', 'insurance_type' => 'directors_officers', 'rate_table_product_type' => 'directors_officers', 'min_premium' => 200, 'max_premium' => 1500, 'deductible_options' => [5000,10000,25000], 'coverage_options' => ['$1,000,000','$5,000,000','$10,000,000'], 'features' => ['Side A DIC','Entity Coverage','Investigation Costs','Pre-Claim Inquiry']],
                ],
            ],
            [
                'name' => 'The Hartford', 'slug' => 'the-hartford',
                'naic_code' => '29459', 'naic_group_code' => '0466',
                'domicile_state' => 'CT', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XV', 'year_founded' => 1810,
                'naic_complaint_ratio' => 0.68, 'market_segment' => 'commercial',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Hartford', 'headquarters_state' => 'CT',
                'total_premium_written' => 22000.00,
                'description' => 'Small business insurance leader — AARP auto and home partner.',
                'lines_of_business' => ['auto','homeowners','bop','workers_comp','commercial_gl','commercial_auto','professional_liability','umbrella_commercial'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Hartford BOP', 'insurance_type' => 'bop', 'rate_table_product_type' => 'bop', 'min_premium' => 120, 'max_premium' => 450, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$300,000','$500,000','$1,000,000','$2,000,000'], 'features' => ['Spectrum Business Package','Data Breach','Equipment Breakdown','Business Income']],
                    ['name' => 'Hartford Workers Comp', 'insurance_type' => 'workers_comp', 'rate_table_product_type' => 'workers_comp', 'min_premium' => 150, 'max_premium' => 600, 'deductible_options' => [500,1000], 'coverage_options' => ['State Statutory','$500,000','$1,000,000'], 'features' => ['Pay-As-You-Go','Nurse Hotline','Return-to-Work']],
                ],
            ],
            [
                'name' => 'Amica Mutual', 'slug' => 'amica',
                'naic_code' => '19976', 'naic_group_code' => '0013',
                'domicile_state' => 'RI', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XIII', 'year_founded' => 1907,
                'naic_complaint_ratio' => 0.38, 'market_segment' => 'personal',
                'distribution_model' => 'direct',
                'headquarters_city' => 'Lincoln', 'headquarters_state' => 'RI',
                'total_premium_written' => 3800.00,
                'description' => 'Policyholder-owned mutual with consistently top customer satisfaction.',
                'lines_of_business' => ['auto','homeowners','umbrella_personal','life_term'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Amica Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 75, 'max_premium' => 210, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$50,000','$100,000','$250,000','$500,000'], 'features' => ['Dividend Eligible','Accident Forgiveness','OEM Parts','Glass Deductible Waiver']],
                ],
            ],
            [
                'name' => 'Safeco (Liberty Mutual)', 'slug' => 'safeco',
                'naic_code' => '24740', 'naic_group_code' => '0111',
                'domicile_state' => 'WA', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'XV', 'year_founded' => 1923,
                'naic_complaint_ratio' => 0.88, 'market_segment' => 'personal',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Boston', 'headquarters_state' => 'MA',
                'total_premium_written' => 7000.00,
                'description' => 'Liberty Mutual\'s independent agent channel for personal lines.',
                'lines_of_business' => ['auto','homeowners','renters','condo','umbrella_personal','motorcycle','boat_watercraft'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Safeco Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 75, 'max_premium' => 220, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$50,000','$100,000','$250,000'], 'features' => ['RightTrack Telematics','Multi-Policy','Claims-Free Discount']],
                    ['name' => 'Safeco Homeowners', 'insurance_type' => 'homeowners', 'rate_table_product_type' => 'homeowners', 'min_premium' => 90, 'max_premium' => 350, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$200,000','$350,000','$500,000'], 'features' => ['Replacement Cost','Personal Property Plus','Equipment Breakdown']],
                ],
            ],
            [
                'name' => 'Cincinnati Financial', 'slug' => 'cincinnati-financial',
                'naic_code' => '10677', 'naic_group_code' => '0172',
                'domicile_state' => 'OH', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XIV', 'year_founded' => 1950,
                'naic_complaint_ratio' => 0.55, 'market_segment' => 'multi',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Fairfield', 'headquarters_state' => 'OH',
                'total_premium_written' => 8500.00,
                'description' => 'Relationship-focused carrier — independent agent exclusive.',
                'lines_of_business' => ['auto','homeowners','commercial_gl','bop','workers_comp','umbrella_commercial','life_term','surety_bond'],
                'states_available' => ['AL','AR','CO','FL','GA','IA','IL','IN','KS','KY','LA','MI','MN','MO','MS','NC','NE','NM','NV','OH','OK','OR','PA','SC','TN','TX','UT','VA','WA','WI','WV'],
                'products' => [
                    ['name' => 'Cincinnati BOP', 'insurance_type' => 'bop', 'rate_table_product_type' => 'bop', 'min_premium' => 130, 'max_premium' => 500, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000'], 'features' => ['Broad Coverage','Equipment Breakdown','Business Income','EPLI']],
                    ['name' => 'Cincinnati Surety', 'insurance_type' => 'surety_bond', 'rate_table_product_type' => 'surety_bond', 'min_premium' => 50, 'max_premium' => 500, 'deductible_options' => [], 'coverage_options' => ['$25,000','$100,000','$500,000','$1,000,000'], 'features' => ['Contract Bonds','Commercial Bonds','License & Permit','Court Bonds']],
                ],
            ],
            [
                'name' => 'Shelter Insurance', 'slug' => 'shelter',
                'naic_code' => '23388', 'naic_group_code' => '0605',
                'domicile_state' => 'MO', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XII', 'year_founded' => 1946,
                'naic_complaint_ratio' => 0.52, 'market_segment' => 'personal',
                'distribution_model' => 'captive',
                'headquarters_city' => 'Columbia', 'headquarters_state' => 'MO',
                'total_premium_written' => 3200.00,
                'description' => 'Midwestern mutual carrier with strong community presence.',
                'lines_of_business' => ['auto','homeowners','life_term','life_whole'],
                'states_available' => ['AR','CO','IL','IN','IA','KS','KY','LA','MO','MS','NE','OH','OK','TN'],
                'products' => [
                    ['name' => 'Shelter Auto', 'insurance_type' => 'auto', 'rate_table_product_type' => 'auto', 'min_premium' => 65, 'max_premium' => 180, 'deductible_options' => [250,500,1000], 'coverage_options' => ['$25,000','$50,000','$100,000','$250,000'], 'features' => ['Good Student','Multi-Car','Defensive Driver']],
                ],
            ],

            // ─── Life Insurance & Annuities ─────────────────────
            [
                'name' => 'MetLife', 'slug' => 'metlife',
                'naic_code' => '65978', 'naic_group_code' => '0540',
                'domicile_state' => 'NY', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XV', 'year_founded' => 1868,
                'naic_complaint_ratio' => 0.88, 'market_segment' => 'life_health',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'New York', 'headquarters_state' => 'NY',
                'total_premium_written' => 45000.00,
                'description' => 'Global insurance leader — life, dental, disability, and group benefits.',
                'lines_of_business' => ['life_term','life_whole','life_universal','annuity','dental','vision','disability_short_term','disability_long_term','long_term_care'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'MetLife Term Life', 'insurance_type' => 'life_term', 'rate_table_product_type' => 'life_term', 'min_premium' => 18, 'max_premium' => 140, 'deductible_options' => [], 'coverage_options' => ['$100,000','$250,000','$500,000','$1,000,000','$2,000,000'], 'features' => ['Level Premium','Convertible','Accelerated Benefits','Terminal Illness']],
                    ['name' => 'MetLife Whole Life', 'insurance_type' => 'life_whole', 'rate_table_product_type' => 'life_whole', 'min_premium' => 45, 'max_premium' => 350, 'deductible_options' => [], 'coverage_options' => ['$25,000','$50,000','$100,000','$250,000'], 'features' => ['Cash Value','Dividend Eligible','Paid-Up Additions','Loan Provision']],
                    ['name' => 'MetLife Dental', 'insurance_type' => 'dental', 'rate_table_product_type' => 'dental', 'min_premium' => 20, 'max_premium' => 80, 'deductible_options' => [0,50,100], 'coverage_options' => ['$1,000','$1,500','$2,000','$3,000'], 'features' => ['Preventive 100%','Basic 80%','Major 50%','Orthodontia']],
                    ['name' => 'MetLife LTD', 'insurance_type' => 'disability_long_term', 'rate_table_product_type' => 'disability_long_term', 'min_premium' => 30, 'max_premium' => 200, 'deductible_options' => [], 'coverage_options' => ['60% of salary','66.67% of salary'], 'features' => ['Own Occupation','COLA Rider','Mental Health Parity','Rehabilitation']],
                ],
            ],
            [
                'name' => 'Prudential Financial', 'slug' => 'prudential',
                'naic_code' => '68241', 'naic_group_code' => '0655',
                'domicile_state' => 'NJ', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XV', 'year_founded' => 1875,
                'naic_complaint_ratio' => 0.76, 'market_segment' => 'life_health',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'Newark', 'headquarters_state' => 'NJ',
                'total_premium_written' => 38000.00,
                'description' => 'The Rock — a leading provider of life insurance, annuities, and retirement.',
                'lines_of_business' => ['life_term','life_whole','life_universal','annuity','disability_long_term','long_term_care'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Prudential Term Essential', 'insurance_type' => 'life_term', 'rate_table_product_type' => 'life_term', 'min_premium' => 15, 'max_premium' => 130, 'deductible_options' => [], 'coverage_options' => ['$100,000','$250,000','$500,000','$1,000,000','$3,000,000'], 'features' => ['Simplified Issue','Level Premium','Convertible','Living Needs']],
                    ['name' => 'Prudential Universal Life', 'insurance_type' => 'life_universal', 'rate_table_product_type' => 'life_universal', 'min_premium' => 60, 'max_premium' => 500, 'deductible_options' => [], 'coverage_options' => ['$100,000','$250,000','$500,000','$1,000,000'], 'features' => ['Flexible Premiums','Cash Value Accumulation','No-Lapse Guarantee','Index Options']],
                    ['name' => 'Prudential Annuity', 'insurance_type' => 'annuity', 'rate_table_product_type' => 'annuity', 'min_premium' => 100, 'max_premium' => 1000, 'deductible_options' => [], 'coverage_options' => ['$50,000','$100,000','$250,000','$500,000'], 'features' => ['Fixed Rate','Index Options','Lifetime Income','Death Benefit']],
                ],
            ],
            [
                'name' => 'New York Life', 'slug' => 'new-york-life',
                'naic_code' => '66915', 'naic_group_code' => '0626',
                'domicile_state' => 'NY', 'am_best_rating' => 'A++',
                'am_best_financial_size' => 'XV', 'year_founded' => 1845,
                'naic_complaint_ratio' => 0.45, 'market_segment' => 'life_health',
                'distribution_model' => 'captive',
                'headquarters_city' => 'New York', 'headquarters_state' => 'NY',
                'total_premium_written' => 32000.00,
                'description' => 'Largest mutual life insurance company in the US — A++ rated since 1938.',
                'lines_of_business' => ['life_term','life_whole','life_universal','annuity','long_term_care','disability_long_term'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'NYL Term Life', 'insurance_type' => 'life_term', 'rate_table_product_type' => 'life_term', 'min_premium' => 20, 'max_premium' => 150, 'deductible_options' => [], 'coverage_options' => ['$100,000','$250,000','$500,000','$1,000,000','$5,000,000'], 'features' => ['Level Premium','Convertible','Accelerated Death Benefit','Dividend Eligible']],
                    ['name' => 'NYL Whole Life', 'insurance_type' => 'life_whole', 'rate_table_product_type' => 'life_whole', 'min_premium' => 50, 'max_premium' => 400, 'deductible_options' => [], 'coverage_options' => ['$25,000','$100,000','$250,000','$500,000','$1,000,000'], 'features' => ['Cash Value','Guaranteed Dividends','Paid-Up Additions','Loan Provision']],
                    ['name' => 'NYL LTC', 'insurance_type' => 'long_term_care', 'rate_table_product_type' => 'long_term_care', 'min_premium' => 80, 'max_premium' => 400, 'deductible_options' => [], 'coverage_options' => ['$150/day','$200/day','$300/day','$400/day'], 'features' => ['Inflation Protection','Home Care','Nursing Facility','Shared Care']],
                ],
            ],
            [
                'name' => 'Northwestern Mutual', 'slug' => 'northwestern-mutual',
                'naic_code' => '67814', 'naic_group_code' => '0628',
                'domicile_state' => 'WI', 'am_best_rating' => 'A++',
                'am_best_financial_size' => 'XV', 'year_founded' => 1857,
                'naic_complaint_ratio' => 0.30, 'market_segment' => 'life_health',
                'distribution_model' => 'captive',
                'headquarters_city' => 'Milwaukee', 'headquarters_state' => 'WI',
                'total_premium_written' => 28000.00,
                'description' => 'The Quiet Company — consistently top-ranked for financial strength and dividends.',
                'lines_of_business' => ['life_term','life_whole','life_universal','annuity','disability_long_term','long_term_care'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'NWM Term Life', 'insurance_type' => 'life_term', 'rate_table_product_type' => 'life_term', 'min_premium' => 22, 'max_premium' => 160, 'deductible_options' => [], 'coverage_options' => ['$250,000','$500,000','$1,000,000','$5,000,000'], 'features' => ['Level Premium','Convertible','Dividend Purchase','Waiver of Premium']],
                    ['name' => 'NWM Whole Life', 'insurance_type' => 'life_whole', 'rate_table_product_type' => 'life_whole', 'min_premium' => 60, 'max_premium' => 500, 'deductible_options' => [], 'coverage_options' => ['$50,000','$100,000','$250,000','$1,000,000'], 'features' => ['Highest Dividends','Cash Value','Paid-Up Options','Estate Planning']],
                    ['name' => 'NWM Individual DI', 'insurance_type' => 'disability_long_term', 'rate_table_product_type' => 'disability_long_term', 'min_premium' => 40, 'max_premium' => 250, 'deductible_options' => [], 'coverage_options' => ['$2,000/mo','$5,000/mo','$10,000/mo','$15,000/mo'], 'features' => ['Own Occupation','COLA','Future Increase','Residual Disability']],
                ],
            ],
            [
                'name' => 'MassMutual', 'slug' => 'massmutual',
                'naic_code' => '65935', 'naic_group_code' => '0515',
                'domicile_state' => 'MA', 'am_best_rating' => 'A++',
                'am_best_financial_size' => 'XV', 'year_founded' => 1851,
                'naic_complaint_ratio' => 0.42, 'market_segment' => 'life_health',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'Springfield', 'headquarters_state' => 'MA',
                'total_premium_written' => 20000.00,
                'description' => 'Mutual carrier — whole life, disability income, and retirement solutions.',
                'lines_of_business' => ['life_term','life_whole','life_universal','annuity','disability_long_term'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'MassMutual Whole Life', 'insurance_type' => 'life_whole', 'rate_table_product_type' => 'life_whole', 'min_premium' => 55, 'max_premium' => 450, 'deductible_options' => [], 'coverage_options' => ['$50,000','$100,000','$250,000','$1,000,000'], 'features' => ['Dividend Eligible','Cash Value Growth','Paid-Up Additions','Loan Access']],
                    ['name' => 'MassMutual DI', 'insurance_type' => 'disability_long_term', 'rate_table_product_type' => 'disability_long_term', 'min_premium' => 35, 'max_premium' => 220, 'deductible_options' => [], 'coverage_options' => ['$2,000/mo','$5,000/mo','$10,000/mo'], 'features' => ['Own Occupation','COLA','Residual','Recovery Benefit']],
                ],
            ],
            [
                'name' => 'Lincoln Financial', 'slug' => 'lincoln-financial',
                'naic_code' => '65676', 'naic_group_code' => '0524',
                'domicile_state' => 'IN', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XV', 'year_founded' => 1905,
                'naic_complaint_ratio' => 0.65, 'market_segment' => 'life_health',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Radnor', 'headquarters_state' => 'PA',
                'total_premium_written' => 16000.00,
                'description' => 'Life insurance, annuities, and employer-sponsored benefits.',
                'lines_of_business' => ['life_term','life_whole','life_universal','annuity','disability_long_term','disability_short_term'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Lincoln TermAccel', 'insurance_type' => 'life_term', 'rate_table_product_type' => 'life_term', 'min_premium' => 16, 'max_premium' => 120, 'deductible_options' => [], 'coverage_options' => ['$100,000','$250,000','$500,000','$1,000,000'], 'features' => ['Accelerated Underwriting','Level Premium','Convertible','Chronic Illness']],
                    ['name' => 'Lincoln IUL', 'insurance_type' => 'life_universal', 'rate_table_product_type' => 'life_universal', 'min_premium' => 75, 'max_premium' => 600, 'deductible_options' => [], 'coverage_options' => ['$100,000','$250,000','$500,000','$1,000,000'], 'features' => ['Index-Linked Growth','No-Lapse Guarantee','Multiplier','Flexible Premiums']],
                ],
            ],
            [
                'name' => 'Transamerica', 'slug' => 'transamerica',
                'naic_code' => '86231', 'naic_group_code' => '2750',
                'domicile_state' => 'IA', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'XV', 'year_founded' => 1928,
                'naic_complaint_ratio' => 1.10, 'market_segment' => 'life_health',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Cedar Rapids', 'headquarters_state' => 'IA',
                'total_premium_written' => 12000.00,
                'description' => 'Global life insurer — life, retirement, and employee benefits.',
                'lines_of_business' => ['life_term','life_whole','life_universal','life_final_expense','annuity','long_term_care'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Transamerica Term', 'insurance_type' => 'life_term', 'rate_table_product_type' => 'life_term', 'min_premium' => 14, 'max_premium' => 110, 'deductible_options' => [], 'coverage_options' => ['$100,000','$250,000','$500,000','$1,000,000'], 'features' => ['Trendsetter','Level Premium','Convertible','Chronic Illness Rider']],
                    ['name' => 'Transamerica Final Expense', 'insurance_type' => 'life_final_expense', 'rate_table_product_type' => 'life_final_expense', 'min_premium' => 20, 'max_premium' => 80, 'deductible_options' => [], 'coverage_options' => ['$5,000','$10,000','$15,000','$25,000'], 'features' => ['Guaranteed Issue','Simplified Issue','No Medical Exam','Immediate Coverage']],
                ],
            ],
            [
                'name' => 'Mutual of Omaha', 'slug' => 'mutual-of-omaha',
                'naic_code' => '71412', 'naic_group_code' => '0569',
                'domicile_state' => 'NE', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XIV', 'year_founded' => 1909,
                'naic_complaint_ratio' => 0.72, 'market_segment' => 'life_health',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Omaha', 'headquarters_state' => 'NE',
                'total_premium_written' => 8000.00,
                'description' => 'Life, disability, and Medicare supplement specialist.',
                'lines_of_business' => ['life_term','life_whole','life_final_expense','disability_long_term','disability_short_term','medicare_supplement','long_term_care'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Mutual of Omaha Term Life', 'insurance_type' => 'life_term', 'rate_table_product_type' => 'life_term', 'min_premium' => 15, 'max_premium' => 120, 'deductible_options' => [], 'coverage_options' => ['$100,000','$250,000','$500,000','$1,000,000'], 'features' => ['Income Advantage','Level Premium','Convertible','Chronic Illness']],
                    ['name' => 'Mutual of Omaha Medicare Supplement', 'insurance_type' => 'medicare_supplement', 'rate_table_product_type' => 'medicare_supplement', 'min_premium' => 100, 'max_premium' => 350, 'deductible_options' => [], 'coverage_options' => ['Plan A','Plan F','Plan G','Plan N'], 'features' => ['Guaranteed Renewable','No Network Restrictions','Any Doctor','Part B Excess']],
                    ['name' => 'Mutual of Omaha DI', 'insurance_type' => 'disability_long_term', 'rate_table_product_type' => 'disability_long_term', 'min_premium' => 30, 'max_premium' => 180, 'deductible_options' => [], 'coverage_options' => ['$1,500/mo','$3,000/mo','$5,000/mo','$10,000/mo'], 'features' => ['Own Occupation','COLA','Residual','Future Purchase']],
                ],
            ],
            [
                'name' => 'Guardian Life', 'slug' => 'guardian-life',
                'naic_code' => '64246', 'naic_group_code' => '0461',
                'domicile_state' => 'NY', 'am_best_rating' => 'A++',
                'am_best_financial_size' => 'XV', 'year_founded' => 1860,
                'naic_complaint_ratio' => 0.48, 'market_segment' => 'life_health',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'New York', 'headquarters_state' => 'NY',
                'total_premium_written' => 14000.00,
                'description' => 'Mutual company — life, DI, dental, vision, and group benefits leader.',
                'lines_of_business' => ['life_term','life_whole','life_universal','disability_long_term','disability_short_term','dental','vision'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Guardian Whole Life', 'insurance_type' => 'life_whole', 'rate_table_product_type' => 'life_whole', 'min_premium' => 50, 'max_premium' => 400, 'deductible_options' => [], 'coverage_options' => ['$50,000','$100,000','$250,000','$500,000'], 'features' => ['Dividend Eligible','Cash Value','Paid-Up Additions','Living Benefits']],
                    ['name' => 'Guardian Individual DI', 'insurance_type' => 'disability_long_term', 'rate_table_product_type' => 'disability_long_term', 'min_premium' => 35, 'max_premium' => 230, 'deductible_options' => [], 'coverage_options' => ['$2,000/mo','$5,000/mo','$10,000/mo','$15,000/mo'], 'features' => ['True Own Occupation','COLA','Future Increase','Catastrophic','Recovery']],
                    ['name' => 'Guardian Dental', 'insurance_type' => 'dental', 'rate_table_product_type' => 'dental', 'min_premium' => 25, 'max_premium' => 85, 'deductible_options' => [0,50,100], 'coverage_options' => ['$1,500','$2,000','$3,000'], 'features' => ['Preventive 100%','Basic 80%','Major 50%','Large Network']],
                ],
            ],
            [
                'name' => 'Unum', 'slug' => 'unum',
                'naic_code' => '62235', 'naic_group_code' => '0605',
                'domicile_state' => 'ME', 'am_best_rating' => 'A-',
                'am_best_financial_size' => 'XIV', 'year_founded' => 1848,
                'naic_complaint_ratio' => 0.95, 'market_segment' => 'life_health',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Chattanooga', 'headquarters_state' => 'TN',
                'total_premium_written' => 7500.00,
                'description' => 'Largest disability income insurance provider in North America.',
                'lines_of_business' => ['disability_short_term','disability_long_term','life_term','life_whole','long_term_care','dental','vision'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Unum Individual DI', 'insurance_type' => 'disability_long_term', 'rate_table_product_type' => 'disability_long_term', 'min_premium' => 25, 'max_premium' => 200, 'deductible_options' => [], 'coverage_options' => ['$1,500/mo','$3,000/mo','$5,000/mo','$10,000/mo'], 'features' => ['Own Occupation','COLA','Residual','Catastrophic Disability','SIS Discount']],
                    ['name' => 'Unum STD', 'insurance_type' => 'disability_short_term', 'rate_table_product_type' => 'disability_short_term', 'min_premium' => 15, 'max_premium' => 80, 'deductible_options' => [], 'coverage_options' => ['60% of salary','66.67% of salary','70% of salary'], 'features' => ['7-Day Elimination','14-Day Elimination','Maternity','Mental Health']],
                ],
            ],
            [
                'name' => 'Principal Financial', 'slug' => 'principal',
                'naic_code' => '61271', 'naic_group_code' => '0660',
                'domicile_state' => 'IA', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XV', 'year_founded' => 1879,
                'naic_complaint_ratio' => 0.58, 'market_segment' => 'life_health',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Des Moines', 'headquarters_state' => 'IA',
                'total_premium_written' => 11000.00,
                'description' => 'Global financial institution — group benefits, retirement, and asset management.',
                'lines_of_business' => ['life_term','life_whole','disability_short_term','disability_long_term','dental','vision','annuity'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Principal Group Life', 'insurance_type' => 'life_term', 'rate_table_product_type' => 'life_term', 'min_premium' => 12, 'max_premium' => 100, 'deductible_options' => [], 'coverage_options' => ['1x Salary','2x Salary','$50,000','$100,000','$500,000'], 'features' => ['Group Rates','Conversion Privilege','AD&D','Supplemental']],
                    ['name' => 'Principal Group DI', 'insurance_type' => 'disability_long_term', 'rate_table_product_type' => 'disability_long_term', 'min_premium' => 20, 'max_premium' => 150, 'deductible_options' => [], 'coverage_options' => ['60% of salary','66.67% of salary'], 'features' => ['Group Rates','Own Occupation 2yr','COLA','Rehabilitation']],
                ],
            ],

            // ─── Health / Medicare ──────────────────────────────
            [
                'name' => 'UnitedHealthcare', 'slug' => 'unitedhealthcare',
                'naic_code' => '79413', 'naic_group_code' => '0638',
                'domicile_state' => 'CT', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XV', 'year_founded' => 1977,
                'naic_complaint_ratio' => 1.25, 'market_segment' => 'life_health',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'Minnetonka', 'headquarters_state' => 'MN',
                'total_premium_written' => 220000.00,
                'description' => 'Largest health insurer in the US by enrollment and revenue.',
                'lines_of_business' => ['health_individual','health_group','dental','vision','medicare_advantage','medicare_supplement','prescription_drug'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'UHC Individual Health', 'insurance_type' => 'health_individual', 'rate_table_product_type' => 'health_individual', 'min_premium' => 250, 'max_premium' => 800, 'deductible_options' => [1000,2500,5000,7500], 'coverage_options' => ['Bronze','Silver','Gold','Platinum'], 'features' => ['Preventive Care','Prescription','Mental Health','Telehealth']],
                    ['name' => 'UHC Medicare Advantage', 'insurance_type' => 'medicare_advantage', 'rate_table_product_type' => 'medicare_advantage', 'min_premium' => 0, 'max_premium' => 150, 'deductible_options' => [0,250,500], 'coverage_options' => ['HMO','PPO','PFFS'], 'features' => ['$0 Premium Options','Part D Included','Dental+Vision','Fitness Benefit']],
                ],
            ],
            [
                'name' => 'Anthem (Elevance Health)', 'slug' => 'anthem',
                'naic_code' => '60217', 'naic_group_code' => '4241',
                'domicile_state' => 'IN', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'XV', 'year_founded' => 2004,
                'naic_complaint_ratio' => 1.15, 'market_segment' => 'life_health',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'Indianapolis', 'headquarters_state' => 'IN',
                'total_premium_written' => 115000.00,
                'description' => 'Blue Cross Blue Shield licensee — second largest health insurer in the US.',
                'lines_of_business' => ['health_individual','health_group','dental','vision','medicare_advantage','medicare_supplement','prescription_drug'],
                'states_available' => ['CA','CO','CT','GA','IN','KY','ME','MO','NH','NV','NY','OH','VA','WI'],
                'products' => [
                    ['name' => 'Anthem Individual Health', 'insurance_type' => 'health_individual', 'rate_table_product_type' => 'health_individual', 'min_premium' => 240, 'max_premium' => 750, 'deductible_options' => [1000,2500,5000], 'coverage_options' => ['Bronze','Silver','Gold','Platinum'], 'features' => ['Blue Cross Network','Preventive Care','Rx Coverage','LiveHealth Online']],
                ],
            ],
            [
                'name' => 'Aetna (CVS Health)', 'slug' => 'aetna',
                'naic_code' => '60054', 'naic_group_code' => '0001',
                'domicile_state' => 'CT', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'XV', 'year_founded' => 1853,
                'naic_complaint_ratio' => 1.08, 'market_segment' => 'life_health',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'Hartford', 'headquarters_state' => 'CT',
                'total_premium_written' => 75000.00,
                'description' => 'Health insurance giant — now part of CVS Health for integrated care.',
                'lines_of_business' => ['health_individual','health_group','dental','vision','medicare_advantage','medicare_supplement','prescription_drug','disability_short_term','disability_long_term','life_term'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Aetna Individual Health', 'insurance_type' => 'health_individual', 'rate_table_product_type' => 'health_individual', 'min_premium' => 230, 'max_premium' => 700, 'deductible_options' => [1000,2500,5000,7500], 'coverage_options' => ['Bronze','Silver','Gold','Platinum'], 'features' => ['CVS MinuteClinic','Telehealth','Mental Health','Rx Coverage']],
                    ['name' => 'Aetna Dental', 'insurance_type' => 'dental', 'rate_table_product_type' => 'dental', 'min_premium' => 20, 'max_premium' => 75, 'deductible_options' => [0,50,100], 'coverage_options' => ['$1,000','$1,500','$2,000'], 'features' => ['Preventive 100%','Basic 80%','Major 50%','Orthodontia']],
                ],
            ],
            [
                'name' => 'Cigna', 'slug' => 'cigna',
                'naic_code' => '67369', 'naic_group_code' => '0173',
                'domicile_state' => 'CT', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'XV', 'year_founded' => 1982,
                'naic_complaint_ratio' => 0.95, 'market_segment' => 'life_health',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'Bloomfield', 'headquarters_state' => 'CT',
                'total_premium_written' => 48000.00,
                'description' => 'Global health services company — health, pharmacy, and supplemental benefits.',
                'lines_of_business' => ['health_individual','health_group','dental','vision','life_term','disability_short_term','disability_long_term','medicare_supplement'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Cigna Health', 'insurance_type' => 'health_individual', 'rate_table_product_type' => 'health_individual', 'min_premium' => 260, 'max_premium' => 780, 'deductible_options' => [1000,2500,5000], 'coverage_options' => ['Bronze','Silver','Gold','Platinum'], 'features' => ['MDLIVE Telehealth','Behavioral Health','Preventive Care','Rx']],
                ],
            ],
            [
                'name' => 'Humana', 'slug' => 'humana',
                'naic_code' => '73288', 'naic_group_code' => '0900',
                'domicile_state' => 'KY', 'am_best_rating' => 'A-',
                'am_best_financial_size' => 'XV', 'year_founded' => 1961,
                'naic_complaint_ratio' => 1.20, 'market_segment' => 'life_health',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'Louisville', 'headquarters_state' => 'KY',
                'total_premium_written' => 85000.00,
                'description' => 'Major Medicare Advantage provider and health insurance company.',
                'lines_of_business' => ['health_individual','health_group','dental','vision','medicare_advantage','medicare_supplement','prescription_drug'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Humana Medicare Advantage', 'insurance_type' => 'medicare_advantage', 'rate_table_product_type' => 'medicare_advantage', 'min_premium' => 0, 'max_premium' => 120, 'deductible_options' => [0,250], 'coverage_options' => ['HMO','PPO'], 'features' => ['$0 Premium Options','Part D Included','Dental+Vision+Hearing','SilverSneakers']],
                    ['name' => 'Humana Dental', 'insurance_type' => 'dental', 'rate_table_product_type' => 'dental', 'min_premium' => 18, 'max_premium' => 65, 'deductible_options' => [0,50], 'coverage_options' => ['$1,000','$1,500','$2,000'], 'features' => ['Preventive 100%','No Waiting Period','PPO+HMO Options']],
                ],
            ],

            // ─── Commercial Lines ───────────────────────────────
            [
                'name' => 'Zurich Insurance', 'slug' => 'zurich',
                'naic_code' => '16535', 'naic_group_code' => '3255',
                'domicile_state' => 'NY', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XV', 'year_founded' => 1912,
                'naic_complaint_ratio' => 0.65, 'market_segment' => 'commercial',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Schaumburg', 'headquarters_state' => 'IL',
                'total_premium_written' => 18000.00,
                'description' => 'Global commercial insurer — large-account specialty and middle market.',
                'lines_of_business' => ['commercial_gl','commercial_property','bop','workers_comp','commercial_auto','professional_liability','cyber_liability','directors_officers','umbrella_commercial'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Zurich Commercial GL', 'insurance_type' => 'commercial_gl', 'rate_table_product_type' => 'commercial_gl', 'min_premium' => 200, 'max_premium' => 1000, 'deductible_options' => [1000,2500,5000,10000], 'coverage_options' => ['$1,000,000','$2,000,000','$5,000,000'], 'features' => ['Occurrence Form','Products/Completed Ops','Premises Liability','Contractual']],
                    ['name' => 'Zurich Commercial Property', 'insurance_type' => 'commercial_property', 'rate_table_product_type' => 'commercial_property', 'min_premium' => 250, 'max_premium' => 1500, 'deductible_options' => [1000,2500,5000,10000,25000], 'coverage_options' => ['$500,000','$1,000,000','$5,000,000','$10,000,000'], 'features' => ['Replacement Cost','Business Income','Equipment Breakdown','Ordinance & Law']],
                ],
            ],
            [
                'name' => 'CNA Financial', 'slug' => 'cna',
                'naic_code' => '20443', 'naic_group_code' => '0173',
                'domicile_state' => 'IL', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'XV', 'year_founded' => 1897,
                'naic_complaint_ratio' => 0.72, 'market_segment' => 'commercial',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Chicago', 'headquarters_state' => 'IL',
                'total_premium_written' => 12000.00,
                'description' => 'Leading commercial P&C insurer — professional liability specialist.',
                'lines_of_business' => ['commercial_gl','commercial_property','bop','workers_comp','professional_liability','cyber_liability','directors_officers','umbrella_commercial','surety_bond'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'CNA Professional Liability', 'insurance_type' => 'professional_liability', 'rate_table_product_type' => 'professional_liability', 'min_premium' => 150, 'max_premium' => 800, 'deductible_options' => [2500,5000,10000,25000], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000','$5,000,000'], 'features' => ['Claims-Made','Tail Coverage','Defense Costs','Prior Acts']],
                    ['name' => 'CNA BOP', 'insurance_type' => 'bop', 'rate_table_product_type' => 'bop', 'min_premium' => 130, 'max_premium' => 500, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000'], 'features' => ['GL + Property','Business Income','Equipment Breakdown','Cyber']],
                ],
            ],
            [
                'name' => 'Markel', 'slug' => 'markel',
                'naic_code' => '22306', 'naic_group_code' => '2062',
                'domicile_state' => 'VA', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'XV', 'year_founded' => 1930,
                'naic_complaint_ratio' => 0.58, 'market_segment' => 'specialty',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Glen Allen', 'headquarters_state' => 'VA',
                'total_premium_written' => 8500.00,
                'description' => 'Specialty/surplus lines insurer — hard-to-place and niche risks.',
                'lines_of_business' => ['commercial_gl','professional_liability','event_liability','umbrella_commercial','inland_marine'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Markel Event Insurance', 'insurance_type' => 'event_liability', 'rate_table_product_type' => 'event_liability', 'min_premium' => 50, 'max_premium' => 300, 'deductible_options' => [0,250,500], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000'], 'features' => ['Wedding Insurance','Special Event','Cancellation','Host Liquor']],
                    ['name' => 'Markel E&O', 'insurance_type' => 'professional_liability', 'rate_table_product_type' => 'professional_liability', 'min_premium' => 120, 'max_premium' => 600, 'deductible_options' => [1000,2500,5000], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000'], 'features' => ['Claims-Made','Defense Outside Limits','Cyber Endorsement']],
                ],
            ],
            [
                'name' => 'Philadelphia Insurance (PHLY)', 'slug' => 'phly',
                'naic_code' => '18058', 'naic_group_code' => '3548',
                'domicile_state' => 'PA', 'am_best_rating' => 'A++',
                'am_best_financial_size' => 'XIV', 'year_founded' => 1962,
                'naic_complaint_ratio' => 0.45, 'market_segment' => 'commercial',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Bala Cynwyd', 'headquarters_state' => 'PA',
                'total_premium_written' => 5500.00,
                'description' => 'Niche commercial carrier — nonprofits, habitational, professional services.',
                'lines_of_business' => ['commercial_gl','commercial_property','professional_liability','epli','directors_officers','umbrella_commercial'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'PHLY Nonprofit Package', 'insurance_type' => 'bop', 'rate_table_product_type' => 'bop', 'min_premium' => 100, 'max_premium' => 400, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000'], 'features' => ['Nonprofit GL','D&O','Professional Liability','Employment Practices']],
                    ['name' => 'PHLY EPLI', 'insurance_type' => 'epli', 'rate_table_product_type' => 'epli', 'min_premium' => 100, 'max_premium' => 500, 'deductible_options' => [2500,5000,10000], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000'], 'features' => ['Third-Party Coverage','Wage & Hour Defense','Workplace Bullying']],
                ],
            ],
            [
                'name' => 'Next Insurance', 'slug' => 'next-insurance',
                'naic_code' => '10385', 'naic_group_code' => '4955',
                'domicile_state' => 'DE', 'am_best_rating' => 'A-',
                'am_best_financial_size' => 'VIII', 'year_founded' => 2016,
                'naic_complaint_ratio' => 1.30, 'market_segment' => 'commercial',
                'distribution_model' => 'direct',
                'headquarters_city' => 'Palo Alto', 'headquarters_state' => 'CA',
                'total_premium_written' => 1200.00,
                'description' => 'Digital-first small business insurance — instant quotes online.',
                'lines_of_business' => ['commercial_gl','bop','professional_liability','workers_comp','commercial_auto'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Next GL', 'insurance_type' => 'commercial_gl', 'rate_table_product_type' => 'commercial_gl', 'min_premium' => 25, 'max_premium' => 200, 'deductible_options' => [500,1000], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000'], 'features' => ['Instant Quote','Monthly Payments','Certificate Manager','No Broker Required']],
                    ['name' => 'Next BOP', 'insurance_type' => 'bop', 'rate_table_product_type' => 'bop', 'min_premium' => 40, 'max_premium' => 250, 'deductible_options' => [500,1000], 'coverage_options' => ['$500,000','$1,000,000'], 'features' => ['GL + Property','Business Income','Equipment','Instant Certificate']],
                    ['name' => 'Next E&O', 'insurance_type' => 'professional_liability', 'rate_table_product_type' => 'professional_liability', 'min_premium' => 30, 'max_premium' => 200, 'deductible_options' => [1000,2500], 'coverage_options' => ['$250,000','$500,000','$1,000,000'], 'features' => ['Instant Quote','Tech E&O','Cyber Add-On','Defense Costs']],
                ],
            ],
            [
                'name' => 'Hiscox', 'slug' => 'hiscox',
                'naic_code' => '10200', 'naic_group_code' => '4072',
                'domicile_state' => 'IL', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'XIV', 'year_founded' => 1901,
                'naic_complaint_ratio' => 0.82, 'market_segment' => 'commercial',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'New York', 'headquarters_state' => 'NY',
                'total_premium_written' => 2200.00,
                'description' => 'Specialty insurer — small business, professional liability, cyber.',
                'lines_of_business' => ['commercial_gl','professional_liability','cyber_liability','bop'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Hiscox GL', 'insurance_type' => 'commercial_gl', 'rate_table_product_type' => 'commercial_gl', 'min_premium' => 30, 'max_premium' => 250, 'deductible_options' => [500,1000,2500], 'coverage_options' => ['$500,000','$1,000,000','$2,000,000'], 'features' => ['Online Quote','Monthly Billing','Self-Service Portal']],
                    ['name' => 'Hiscox Cyber', 'insurance_type' => 'cyber_liability', 'rate_table_product_type' => 'cyber_liability', 'min_premium' => 40, 'max_premium' => 300, 'deductible_options' => [1000,2500,5000], 'coverage_options' => ['$250,000','$500,000','$1,000,000'], 'features' => ['Data Breach Response','Business Interruption','Social Engineering','Media Liability']],
                ],
            ],

            // ─── Disability & LTC Specialists ───────────────────
            [
                'name' => 'Genworth Financial', 'slug' => 'genworth',
                'naic_code' => '70025', 'naic_group_code' => '3280',
                'domicile_state' => 'VA', 'am_best_rating' => 'B++',
                'am_best_financial_size' => 'XIV', 'year_founded' => 2004,
                'naic_complaint_ratio' => 1.85, 'market_segment' => 'life_health',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Richmond', 'headquarters_state' => 'VA',
                'total_premium_written' => 5500.00,
                'description' => 'Largest long-term care insurance provider in the United States.',
                'lines_of_business' => ['long_term_care','life_term','life_whole'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Genworth LTC', 'insurance_type' => 'long_term_care', 'rate_table_product_type' => 'long_term_care', 'min_premium' => 100, 'max_premium' => 500, 'deductible_options' => [], 'coverage_options' => ['$150/day','$200/day','$250/day','$350/day'], 'features' => ['Home Care','Assisted Living','Nursing Facility','Inflation Protection','Shared Care']],
                ],
            ],
            [
                'name' => 'Standard Insurance', 'slug' => 'standard-insurance',
                'naic_code' => '69019', 'naic_group_code' => '0681',
                'domicile_state' => 'OR', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'XIV', 'year_founded' => 1906,
                'naic_complaint_ratio' => 0.55, 'market_segment' => 'life_health',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Portland', 'headquarters_state' => 'OR',
                'total_premium_written' => 5000.00,
                'description' => 'StanCorp — disability income, life, and retirement plan services.',
                'lines_of_business' => ['disability_long_term','disability_short_term','life_term','annuity'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Standard Individual DI', 'insurance_type' => 'disability_long_term', 'rate_table_product_type' => 'disability_long_term', 'min_premium' => 30, 'max_premium' => 200, 'deductible_options' => [], 'coverage_options' => ['$1,500/mo','$3,000/mo','$5,000/mo','$10,000/mo','$15,000/mo'], 'features' => ['Own Occupation to 65','COLA','Future Increase','Residual','Catastrophic']],
                ],
            ],
            [
                'name' => 'Aflac', 'slug' => 'aflac',
                'naic_code' => '60380', 'naic_group_code' => '0349',
                'domicile_state' => 'GA', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XV', 'year_founded' => 1955,
                'naic_complaint_ratio' => 0.68, 'market_segment' => 'life_health',
                'distribution_model' => 'captive',
                'headquarters_city' => 'Columbus', 'headquarters_state' => 'GA',
                'total_premium_written' => 15000.00,
                'description' => 'Supplemental insurance leader — accident, cancer, hospital, disability.',
                'lines_of_business' => ['disability_short_term','disability_long_term','life_term','health_individual'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Aflac Short-Term Disability', 'insurance_type' => 'disability_short_term', 'rate_table_product_type' => 'disability_short_term', 'min_premium' => 10, 'max_premium' => 60, 'deductible_options' => [], 'coverage_options' => ['$500/mo','$1,000/mo','$2,000/mo','$3,000/mo'], 'features' => ['Day 1 Coverage','Accident + Sickness','Maternity','Mental Health']],
                    ['name' => 'Aflac Accident', 'insurance_type' => 'health_individual', 'rate_table_product_type' => 'health_individual', 'min_premium' => 15, 'max_premium' => 50, 'deductible_options' => [], 'coverage_options' => ['$10,000','$25,000','$50,000','$75,000'], 'features' => ['ER Visit','Hospital Stay','Ambulance','Physical Therapy']],
                ],
            ],
            [
                'name' => 'National Guardian Life (NGL)', 'slug' => 'ngl',
                'naic_code' => '66583', 'naic_group_code' => '3055',
                'domicile_state' => 'WI', 'am_best_rating' => 'A',
                'am_best_financial_size' => 'X', 'year_founded' => 1909,
                'naic_complaint_ratio' => 0.90, 'market_segment' => 'life_health',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Madison', 'headquarters_state' => 'WI',
                'total_premium_written' => 1200.00,
                'description' => 'Niche carrier — individual DI and group benefits for small employers.',
                'lines_of_business' => ['disability_long_term','disability_short_term','life_term','dental','vision'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'NGL Individual DI', 'insurance_type' => 'disability_long_term', 'rate_table_product_type' => 'disability_long_term', 'min_premium' => 25, 'max_premium' => 150, 'deductible_options' => [], 'coverage_options' => ['$1,000/mo','$2,500/mo','$5,000/mo','$7,500/mo'], 'features' => ['Own Occupation','COLA','Residual','Future Purchase','Multi-Life Discount']],
                ],
            ],
            [
                'name' => 'Assurity Life', 'slug' => 'assurity',
                'naic_code' => '71439', 'naic_group_code' => '2710',
                'domicile_state' => 'NE', 'am_best_rating' => 'A-',
                'am_best_financial_size' => 'X', 'year_founded' => 1890,
                'naic_complaint_ratio' => 0.72, 'market_segment' => 'life_health',
                'distribution_model' => 'independent',
                'headquarters_city' => 'Lincoln', 'headquarters_state' => 'NE',
                'total_premium_written' => 800.00,
                'description' => 'Individual DI, life, and critical illness specialist.',
                'lines_of_business' => ['disability_long_term','life_term','life_whole'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Assurity Individual DI', 'insurance_type' => 'disability_long_term', 'rate_table_product_type' => 'disability_long_term', 'min_premium' => 20, 'max_premium' => 130, 'deductible_options' => [], 'coverage_options' => ['$1,000/mo','$2,500/mo','$5,000/mo'], 'features' => ['Own Occupation','COLA','Residual','Non-Cancellable','Guaranteed Renewable']],
                ],
            ],

            // ─── Specialty ──────────────────────────────────────
            [
                'name' => 'Trupanion', 'slug' => 'trupanion',
                'naic_code' => '12190', 'naic_group_code' => '4705',
                'domicile_state' => 'WA', 'am_best_rating' => 'A-',
                'am_best_financial_size' => 'IX', 'year_founded' => 2000,
                'naic_complaint_ratio' => 1.15, 'market_segment' => 'specialty',
                'distribution_model' => 'direct',
                'headquarters_city' => 'Seattle', 'headquarters_state' => 'WA',
                'total_premium_written' => 900.00,
                'description' => 'Leading pet insurance provider — direct vet payment model.',
                'lines_of_business' => ['pet'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Trupanion Pet', 'insurance_type' => 'pet', 'rate_table_product_type' => 'pet', 'min_premium' => 30, 'max_premium' => 120, 'deductible_options' => [0,100,250,500,1000], 'coverage_options' => ['90% Reimbursement','Unlimited Lifetime'], 'features' => ['Direct Vet Payment','No Payout Limits','Hereditary Conditions','Hip Dysplasia']],
                ],
            ],
            [
                'name' => 'Allianz Global Assistance', 'slug' => 'allianz-travel',
                'naic_code' => '39300', 'naic_group_code' => '3255',
                'domicile_state' => 'VA', 'am_best_rating' => 'A+',
                'am_best_financial_size' => 'XV', 'year_founded' => 1890,
                'naic_complaint_ratio' => 0.78, 'market_segment' => 'specialty',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'Richmond', 'headquarters_state' => 'VA',
                'total_premium_written' => 2000.00,
                'description' => 'Leading travel insurance provider — trip cancellation and medical coverage.',
                'lines_of_business' => ['travel'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'Allianz Travel Protection', 'insurance_type' => 'travel', 'rate_table_product_type' => 'travel', 'min_premium' => 20, 'max_premium' => 200, 'deductible_options' => [0,100,250], 'coverage_options' => ['$10,000','$25,000','$50,000','$100,000'], 'features' => ['Trip Cancellation','Medical Emergency','Baggage Loss','24/7 Assistance']],
                ],
            ],
            [
                'name' => 'National Flood Insurance Program (NFIP)', 'slug' => 'nfip',
                'naic_code' => '00000', 'naic_group_code' => '0000',
                'domicile_state' => 'DC', 'am_best_rating' => 'NR',
                'year_founded' => 1968,
                'naic_complaint_ratio' => null, 'market_segment' => 'specialty',
                'distribution_model' => 'hybrid',
                'headquarters_city' => 'Washington', 'headquarters_state' => 'DC',
                'total_premium_written' => 4000.00,
                'description' => 'Federal program providing flood insurance through Write Your Own carriers.',
                'lines_of_business' => ['flood'],
                'states_available' => $all,
                'products' => [
                    ['name' => 'NFIP Flood Insurance', 'insurance_type' => 'flood', 'rate_table_product_type' => 'flood', 'min_premium' => 30, 'max_premium' => 300, 'deductible_options' => [1000,2000,5000,10000], 'coverage_options' => ['$100,000','$150,000','$250,000'], 'features' => ['Building Coverage','Contents Coverage','Risk Rating 2.0','Increased Cost of Compliance']],
                ],
            ],
        ];
    }
}
