<?php

namespace App\Console\Commands;

/**
 * Registry of all 50 US state + DC Department of Insurance (DOI) license data sources.
 *
 * Each entry contains:
 *  - name:       State DOI / regulatory body name
 *  - abbr:       2-letter state abbreviation
 *  - source_key: Unique key used in agent_profiles.source (e.g. 'fl_dfs')
 *  - bulk_url:   URL to bulk download page (or API endpoint)
 *  - lookup_url: Pattern for individual license lookup ({license} is replaced)
 *  - format:     Expected file format (csv, xlsx, pipe-delimited, api)
 *  - notes:      Special instructions for downloading or parsing
 *  - has_npn:    Whether the bulk data includes NPN
 *  - column_hints: State-specific header aliases to help auto-detection
 */
class StateLicenseSources
{
    public static function all(): array
    {
        return [
            'AL' => [
                'name' => 'Alabama Department of Insurance',
                'abbr' => 'AL',
                'source_key' => 'al_doi',
                'bulk_url' => 'https://www.aldoi.gov/LicenseeSearch.aspx',
                'lookup_url' => 'https://www.aldoi.gov/LicenseeSearch.aspx',
                'format' => 'csv',
                'notes' => 'Bulk download via ALDOI Licensee Search export.',
                'has_npn' => true,
                'column_hints' => ['licensee_name' => ['licensee_name', 'agent_name']],
            ],
            'AK' => [
                'name' => 'Alaska Division of Insurance',
                'abbr' => 'AK',
                'source_key' => 'ak_doi',
                'bulk_url' => 'https://www.commerce.alaska.gov/web/ins/LicensingProducers.aspx',
                'lookup_url' => 'https://www.commerce.alaska.gov/web/ins/LicensingProducers.aspx',
                'format' => 'csv',
                'notes' => 'Download from Alaska Division of Insurance producer search.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'AZ' => [
                'name' => 'Arizona Department of Insurance & Financial Institutions',
                'abbr' => 'AZ',
                'source_key' => 'az_difi',
                'bulk_url' => 'https://insurance.az.gov/licensee-search',
                'lookup_url' => 'https://insurance.az.gov/licensee-search',
                'format' => 'csv',
                'notes' => 'Arizona DIFI licensee search with export option.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'AR' => [
                'name' => 'Arkansas Insurance Department',
                'abbr' => 'AR',
                'source_key' => 'ar_aid',
                'bulk_url' => 'https://insurance.arkansas.gov/pages/license-lookup/',
                'lookup_url' => 'https://insurance.arkansas.gov/pages/license-lookup/',
                'format' => 'csv',
                'notes' => 'Arkansas Insurance Department license lookup with download.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'CA' => [
                'name' => 'California Department of Insurance',
                'abbr' => 'CA',
                'source_key' => 'ca_cdi',
                'bulk_url' => 'https://interactive.web.insurance.ca.gov/webuser/ProdLicSrch$SearchForm',
                'lookup_url' => 'https://interactive.web.insurance.ca.gov/webuser/ProdLicSrch$SearchForm?license_number={license}',
                'format' => 'csv',
                'notes' => 'CA CDI provides bulk producer data via data.ca.gov open data portal. Search "insurance producer" on data.ca.gov.',
                'has_npn' => true,
                'column_hints' => ['licensee_name' => ['name', 'producer_name', 'licensee']],
            ],
            'CO' => [
                'name' => 'Colorado Division of Insurance',
                'abbr' => 'CO',
                'source_key' => 'co_doi',
                'bulk_url' => 'https://doi.colorado.gov/insurance-licensing',
                'lookup_url' => 'https://doi.colorado.gov/insurance-licensing',
                'format' => 'csv',
                'notes' => 'Colorado DOI uses NIPR gateway. Bulk data may require NIPR subscription.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'CT' => [
                'name' => 'Connecticut Insurance Department',
                'abbr' => 'CT',
                'source_key' => 'ct_cid',
                'bulk_url' => 'https://portal.ct.gov/CID/License-Services/License-Verification',
                'lookup_url' => 'https://portal.ct.gov/CID/License-Services/License-Verification',
                'format' => 'csv',
                'notes' => 'CT CID license verification portal. Bulk export available for qualified requests.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'DE' => [
                'name' => 'Delaware Department of Insurance',
                'abbr' => 'DE',
                'source_key' => 'de_doi',
                'bulk_url' => 'https://deins.doe.state.de.us/NAICSSearch/',
                'lookup_url' => 'https://deins.doe.state.de.us/NAICSSearch/',
                'format' => 'csv',
                'notes' => 'Delaware DOI NAIC search portal.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'DC' => [
                'name' => 'DC Department of Insurance, Securities and Banking',
                'abbr' => 'DC',
                'source_key' => 'dc_disb',
                'bulk_url' => 'https://disb.dc.gov/page/insurance-producer-licensing',
                'lookup_url' => 'https://disb.dc.gov/page/insurance-producer-licensing',
                'format' => 'csv',
                'notes' => 'DC DISB producer licensing page.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'FL' => [
                'name' => 'Florida Department of Financial Services',
                'abbr' => 'FL',
                'source_key' => 'fl_dfs',
                'bulk_url' => 'https://licenseesearch.fldfs.com/Account/DownloadData',
                'lookup_url' => 'https://licenseesearch.fldfs.com/Licensee/{license}',
                'format' => 'csv',
                'notes' => 'Download "All Valid Licenses - Individual" CSV (~317MB). Direct bulk download available without login.',
                'has_npn' => true,
                'column_hints' => ['licensee_name' => ['licensee_name', 'name']],
            ],
            'GA' => [
                'name' => 'Georgia Office of Insurance and Safety Fire Commissioner',
                'abbr' => 'GA',
                'source_key' => 'ga_oci',
                'bulk_url' => 'https://www.oci.ga.gov/ExternalResources/AgentLookup/',
                'lookup_url' => 'https://www.oci.ga.gov/ExternalResources/AgentLookup/',
                'format' => 'csv',
                'notes' => 'Georgia OCI agent lookup with export. Bulk data available via public records request.',
                'has_npn' => true,
                'column_hints' => ['licensee_name' => ['agent_name', 'name']],
            ],
            'HI' => [
                'name' => 'Hawaii Insurance Division',
                'abbr' => 'HI',
                'source_key' => 'hi_dcca',
                'bulk_url' => 'https://cca.hawaii.gov/ins/licensing/',
                'lookup_url' => 'https://cca.hawaii.gov/ins/licensing/',
                'format' => 'csv',
                'notes' => 'Hawaii DCCA Insurance Division.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'ID' => [
                'name' => 'Idaho Department of Insurance',
                'abbr' => 'ID',
                'source_key' => 'id_doi',
                'bulk_url' => 'https://doi.idaho.gov/licensing/',
                'lookup_url' => 'https://doi.idaho.gov/licensing/',
                'format' => 'csv',
                'notes' => 'Idaho DOI licensing page.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'IL' => [
                'name' => 'Illinois Department of Insurance',
                'abbr' => 'IL',
                'source_key' => 'il_doi',
                'bulk_url' => 'https://online-DOI.insurance.illinois.gov/PRODUCER/ProducerSearch.aspx',
                'lookup_url' => 'https://online-DOI.insurance.illinois.gov/PRODUCER/ProducerSearch.aspx',
                'format' => 'csv',
                'notes' => 'Illinois DOI producer search. Bulk CSV available via open data.',
                'has_npn' => true,
                'column_hints' => ['licensee_name' => ['producer_name', 'name']],
            ],
            'IN' => [
                'name' => 'Indiana Department of Insurance',
                'abbr' => 'IN',
                'source_key' => 'in_doi',
                'bulk_url' => 'https://www.in.gov/idoi/licensing-and-education/',
                'lookup_url' => 'https://www.in.gov/idoi/licensing-and-education/',
                'format' => 'csv',
                'notes' => 'Indiana DOI licensing portal.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'IA' => [
                'name' => 'Iowa Insurance Division',
                'abbr' => 'IA',
                'source_key' => 'ia_iid',
                'bulk_url' => 'https://iid.iowa.gov/producer-licensing',
                'lookup_url' => 'https://iid.iowa.gov/producer-licensing',
                'format' => 'csv',
                'notes' => 'Iowa Insurance Division producer licensing.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'KS' => [
                'name' => 'Kansas Insurance Department',
                'abbr' => 'KS',
                'source_key' => 'ks_kid',
                'bulk_url' => 'https://insurance.kansas.gov/agent-search/',
                'lookup_url' => 'https://insurance.kansas.gov/agent-search/',
                'format' => 'csv',
                'notes' => 'Kansas Insurance Department agent search.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'KY' => [
                'name' => 'Kentucky Department of Insurance',
                'abbr' => 'KY',
                'source_key' => 'ky_doi',
                'bulk_url' => 'https://insurance.ky.gov/ppc/Pages/default.aspx',
                'lookup_url' => 'https://insurance.ky.gov/ppc/Pages/default.aspx',
                'format' => 'csv',
                'notes' => 'Kentucky DOI agent search portal.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'LA' => [
                'name' => 'Louisiana Department of Insurance',
                'abbr' => 'LA',
                'source_key' => 'la_doi',
                'bulk_url' => 'https://www.ldi.la.gov/licensing-702',
                'lookup_url' => 'https://www.ldi.la.gov/licensing-702',
                'format' => 'csv',
                'notes' => 'Louisiana DOI licensing portal. Supports bulk data requests.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'ME' => [
                'name' => 'Maine Bureau of Insurance',
                'abbr' => 'ME',
                'source_key' => 'me_boi',
                'bulk_url' => 'https://www.maine.gov/pfr/insurance/licensing.html',
                'lookup_url' => 'https://www.maine.gov/pfr/insurance/licensing.html',
                'format' => 'csv',
                'notes' => 'Maine Bureau of Insurance.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'MD' => [
                'name' => 'Maryland Insurance Administration',
                'abbr' => 'MD',
                'source_key' => 'md_mia',
                'bulk_url' => 'https://insurance.maryland.gov/Pages/LicenseLookup.aspx',
                'lookup_url' => 'https://insurance.maryland.gov/Pages/LicenseLookup.aspx',
                'format' => 'csv',
                'notes' => 'Maryland MIA license lookup with export functionality.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'MA' => [
                'name' => 'Massachusetts Division of Insurance',
                'abbr' => 'MA',
                'source_key' => 'ma_doi',
                'bulk_url' => 'https://www.mass.gov/orgs/division-of-insurance',
                'lookup_url' => 'https://www.mass.gov/orgs/division-of-insurance',
                'format' => 'csv',
                'notes' => 'Massachusetts DOI. Agent search via NIPR.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'MI' => [
                'name' => 'Michigan Department of Insurance and Financial Services',
                'abbr' => 'MI',
                'source_key' => 'mi_difs',
                'bulk_url' => 'https://difs.state.mi.us/Complaints/Search.aspx',
                'lookup_url' => 'https://difs.state.mi.us/Complaints/Search.aspx',
                'format' => 'csv',
                'notes' => 'Michigan DIFS producer search.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'MN' => [
                'name' => 'Minnesota Department of Commerce',
                'abbr' => 'MN',
                'source_key' => 'mn_doc',
                'bulk_url' => 'https://mn.gov/commerce/industries/insurance/licensing/',
                'lookup_url' => 'https://mn.gov/commerce/industries/insurance/licensing/',
                'format' => 'csv',
                'notes' => 'Minnesota DOC insurance licensing.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'MS' => [
                'name' => 'Mississippi Insurance Department',
                'abbr' => 'MS',
                'source_key' => 'ms_mid',
                'bulk_url' => 'https://www.mid.ms.gov/licensing/agent-search.aspx',
                'lookup_url' => 'https://www.mid.ms.gov/licensing/agent-search.aspx',
                'format' => 'csv',
                'notes' => 'Mississippi Insurance Department agent search.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'MO' => [
                'name' => 'Missouri Department of Commerce and Insurance',
                'abbr' => 'MO',
                'source_key' => 'mo_dci',
                'bulk_url' => 'https://insurance.mo.gov/agents/',
                'lookup_url' => 'https://insurance.mo.gov/agents/',
                'format' => 'csv',
                'notes' => 'Missouri DCI agent licensing.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'MT' => [
                'name' => 'Montana Commissioner of Securities and Insurance',
                'abbr' => 'MT',
                'source_key' => 'mt_csi',
                'bulk_url' => 'https://csimt.gov/insurance/licensing/',
                'lookup_url' => 'https://csimt.gov/insurance/licensing/',
                'format' => 'csv',
                'notes' => 'Montana CSI insurance licensing.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'NE' => [
                'name' => 'Nebraska Department of Insurance',
                'abbr' => 'NE',
                'source_key' => 'ne_doi',
                'bulk_url' => 'https://doi.nebraska.gov/producer',
                'lookup_url' => 'https://doi.nebraska.gov/producer',
                'format' => 'csv',
                'notes' => 'Nebraska DOI producer search.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'NV' => [
                'name' => 'Nevada Division of Insurance',
                'abbr' => 'NV',
                'source_key' => 'nv_doi',
                'bulk_url' => 'https://doi.nv.gov/Licensees/Producer_Licensing/',
                'lookup_url' => 'https://doi.nv.gov/Licensees/Producer_Licensing/',
                'format' => 'csv',
                'notes' => 'Nevada DOI producer licensing.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'NH' => [
                'name' => 'New Hampshire Insurance Department',
                'abbr' => 'NH',
                'source_key' => 'nh_nhid',
                'bulk_url' => 'https://www.nh.gov/insurance/licensing/',
                'lookup_url' => 'https://www.nh.gov/insurance/licensing/',
                'format' => 'csv',
                'notes' => 'New Hampshire Insurance Department.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'NJ' => [
                'name' => 'New Jersey Department of Banking and Insurance',
                'abbr' => 'NJ',
                'source_key' => 'nj_dobi',
                'bulk_url' => 'https://www.state.nj.us/dobi/liclook/acsearch.htm',
                'lookup_url' => 'https://www.state.nj.us/dobi/liclook/acsearch.htm',
                'format' => 'csv',
                'notes' => 'NJ DOBI agent/company search. Bulk download via open data portal.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'NM' => [
                'name' => 'New Mexico Office of Superintendent of Insurance',
                'abbr' => 'NM',
                'source_key' => 'nm_osi',
                'bulk_url' => 'https://www.osi.state.nm.us/licensing/',
                'lookup_url' => 'https://www.osi.state.nm.us/licensing/',
                'format' => 'csv',
                'notes' => 'New Mexico OSI licensing.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'NY' => [
                'name' => 'New York Department of Financial Services',
                'abbr' => 'NY',
                'source_key' => 'ny_dfs',
                'bulk_url' => 'https://myportal.dfs.ny.gov/web/guest-user/insurance-agent-search',
                'lookup_url' => 'https://myportal.dfs.ny.gov/web/guest-user/insurance-agent-search',
                'format' => 'csv',
                'notes' => 'NY DFS agent search portal. Bulk data available via data.ny.gov open data.',
                'has_npn' => true,
                'column_hints' => ['licensee_name' => ['agent_name', 'producer_name']],
            ],
            'NC' => [
                'name' => 'North Carolina Department of Insurance',
                'abbr' => 'NC',
                'source_key' => 'nc_doi',
                'bulk_url' => 'https://www.ncdoi.gov/consumers/agent-lookup',
                'lookup_url' => 'https://www.ncdoi.gov/consumers/agent-lookup',
                'format' => 'csv',
                'notes' => 'NC DOI agent lookup.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'ND' => [
                'name' => 'North Dakota Insurance Department',
                'abbr' => 'ND',
                'source_key' => 'nd_ndid',
                'bulk_url' => 'https://www.insurance.nd.gov/licensing',
                'lookup_url' => 'https://www.insurance.nd.gov/licensing',
                'format' => 'csv',
                'notes' => 'North Dakota Insurance Department.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'OH' => [
                'name' => 'Ohio Department of Insurance',
                'abbr' => 'OH',
                'source_key' => 'oh_doi',
                'bulk_url' => 'https://gateway.insurance.ohio.gov/LicenseSearch/',
                'lookup_url' => 'https://gateway.insurance.ohio.gov/LicenseSearch/',
                'format' => 'csv',
                'notes' => 'Ohio DOI license search gateway. Supports CSV export.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'OK' => [
                'name' => 'Oklahoma Insurance Department',
                'abbr' => 'OK',
                'source_key' => 'ok_oid',
                'bulk_url' => 'https://www.oid.ok.gov/licensing-division/',
                'lookup_url' => 'https://www.oid.ok.gov/licensing-division/',
                'format' => 'csv',
                'notes' => 'Oklahoma Insurance Department.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'OR' => [
                'name' => 'Oregon Division of Financial Regulation',
                'abbr' => 'OR',
                'source_key' => 'or_dfr',
                'bulk_url' => 'https://dfr.oregon.gov/licensing',
                'lookup_url' => 'https://dfr.oregon.gov/licensing',
                'format' => 'csv',
                'notes' => 'Oregon DFR licensing.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'PA' => [
                'name' => 'Pennsylvania Insurance Department',
                'abbr' => 'PA',
                'source_key' => 'pa_pid',
                'bulk_url' => 'https://www.insurance.pa.gov/Licensees/Pages/default.aspx',
                'lookup_url' => 'https://www.insurance.pa.gov/Licensees/Pages/default.aspx',
                'format' => 'csv',
                'notes' => 'Pennsylvania Insurance Department. Bulk data via open data portal.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'RI' => [
                'name' => 'Rhode Island Department of Business Regulation',
                'abbr' => 'RI',
                'source_key' => 'ri_dbr',
                'bulk_url' => 'https://dbr.ri.gov/divisions/insurance/',
                'lookup_url' => 'https://dbr.ri.gov/divisions/insurance/',
                'format' => 'csv',
                'notes' => 'Rhode Island DBR insurance.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'SC' => [
                'name' => 'South Carolina Department of Insurance',
                'abbr' => 'SC',
                'source_key' => 'sc_doi',
                'bulk_url' => 'https://doi.sc.gov/447/Agent-Search',
                'lookup_url' => 'https://doi.sc.gov/447/Agent-Search',
                'format' => 'csv',
                'notes' => 'South Carolina DOI agent search.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'SD' => [
                'name' => 'South Dakota Division of Insurance',
                'abbr' => 'SD',
                'source_key' => 'sd_doi',
                'bulk_url' => 'https://dlr.sd.gov/insurance/licensing/',
                'lookup_url' => 'https://dlr.sd.gov/insurance/licensing/',
                'format' => 'csv',
                'notes' => 'South Dakota Division of Insurance.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'TN' => [
                'name' => 'Tennessee Department of Commerce and Insurance',
                'abbr' => 'TN',
                'source_key' => 'tn_tdci',
                'bulk_url' => 'https://verify.tn.gov/',
                'lookup_url' => 'https://verify.tn.gov/',
                'format' => 'csv',
                'notes' => 'Tennessee TDCI verification portal.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'TX' => [
                'name' => 'Texas Department of Insurance',
                'abbr' => 'TX',
                'source_key' => 'tx_tdi',
                'bulk_url' => 'https://www.tdi.texas.gov/agent/agentsearch.html',
                'lookup_url' => 'https://www.tdi.texas.gov/agent/agentsearch.html',
                'format' => 'csv',
                'notes' => 'TX TDI agent search. Bulk data available via Texas Open Data Portal.',
                'has_npn' => true,
                'column_hints' => ['licensee_name' => ['agent_name', 'producer_name', 'name']],
            ],
            'UT' => [
                'name' => 'Utah Insurance Department',
                'abbr' => 'UT',
                'source_key' => 'ut_uid',
                'bulk_url' => 'https://insurance.utah.gov/licensing',
                'lookup_url' => 'https://insurance.utah.gov/licensing',
                'format' => 'csv',
                'notes' => 'Utah Insurance Department licensing.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'VT' => [
                'name' => 'Vermont Department of Financial Regulation',
                'abbr' => 'VT',
                'source_key' => 'vt_dfr',
                'bulk_url' => 'https://dfr.vermont.gov/insurance/producers',
                'lookup_url' => 'https://dfr.vermont.gov/insurance/producers',
                'format' => 'csv',
                'notes' => 'Vermont DFR producer search.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'VA' => [
                'name' => 'Virginia Bureau of Insurance',
                'abbr' => 'VA',
                'source_key' => 'va_boi',
                'bulk_url' => 'https://scc.virginia.gov/pages/Insurance-Licensing',
                'lookup_url' => 'https://scc.virginia.gov/pages/Insurance-Licensing',
                'format' => 'csv',
                'notes' => 'Virginia SCC Bureau of Insurance.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'WA' => [
                'name' => 'Washington Office of the Insurance Commissioner',
                'abbr' => 'WA',
                'source_key' => 'wa_oic',
                'bulk_url' => 'https://fortress.wa.gov/oic/consumer/default.aspx',
                'lookup_url' => 'https://fortress.wa.gov/oic/consumer/default.aspx',
                'format' => 'csv',
                'notes' => 'Washington OIC consumer search. Bulk data via public records request.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'WV' => [
                'name' => 'West Virginia Insurance Commissioner',
                'abbr' => 'WV',
                'source_key' => 'wv_oic',
                'bulk_url' => 'https://www.wvinsurance.gov/Licensing',
                'lookup_url' => 'https://www.wvinsurance.gov/Licensing',
                'format' => 'csv',
                'notes' => 'West Virginia OIC licensing.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'WI' => [
                'name' => 'Wisconsin Office of the Commissioner of Insurance',
                'abbr' => 'WI',
                'source_key' => 'wi_oci',
                'bulk_url' => 'https://oci.wi.gov/Pages/Agents/AgentSearch.aspx',
                'lookup_url' => 'https://oci.wi.gov/Pages/Agents/AgentSearch.aspx',
                'format' => 'csv',
                'notes' => 'Wisconsin OCI agent search.',
                'has_npn' => true,
                'column_hints' => [],
            ],
            'WY' => [
                'name' => 'Wyoming Department of Insurance',
                'abbr' => 'WY',
                'source_key' => 'wy_doi',
                'bulk_url' => 'https://doi.wyo.gov/licensing',
                'lookup_url' => 'https://doi.wyo.gov/licensing',
                'format' => 'csv',
                'notes' => 'Wyoming DOI licensing.',
                'has_npn' => true,
                'column_hints' => [],
            ],
        ];
    }

    /**
     * Get config for a single state.
     */
    public static function get(string $state): ?array
    {
        return self::all()[strtoupper($state)] ?? null;
    }

    /**
     * Get the source_key for a state (used in agent_profiles.source).
     */
    public static function sourceKey(string $state): string
    {
        $config = self::get($state);
        return $config ? $config['source_key'] : strtolower($state) . '_doi';
    }

    /**
     * Build a license lookup URL for a given state and license number.
     */
    public static function lookupUrl(string $state, string $licenseNumber): ?string
    {
        $config = self::get($state);
        if (!$config) return null;

        $url = $config['lookup_url'];
        return str_replace('{license}', $licenseNumber, $url);
    }

    /**
     * List all available state abbreviations.
     */
    public static function states(): array
    {
        return array_keys(self::all());
    }
}
